version: '3.11'

services:

  dbserver:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg_data2:/var/lib/postgresql/data2/pgdata2
    ports:
      - '5433:5432'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command:  bash -c "ls && flask db upgrade && python app.py"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      dbserver:
        condition: service_healthy

volumes:
  pg_data2:
